CompletableFuture

- Introduced in Java 8
- With more feature than Future
- cfs = CompletableFuture

API:
----------------------------------------------------------------------------------
Start Link
----------------------------------------------------------------------------------
- supplyAsync(func)     - To run background task asynchronously and return something
- runAsync(func)        - To run background task asynchronously and return nothing
----------------------------------------------------------------------------------
Chain Link
----------------------------------------------------------------------------------
- thenApply(func)  - HAS return  - HAS access to result of previous Completable it attached to
- thenAccept(func) - NO return   - HAS access to result of previous Completable it attached to
- thenRun(func)    - NO return   - NO access to result of previous Completable it attached to

- thenCombine(cf, func)     - Go on function chains no nesting - independent from each other
- thenCompose(cf, func)     - Go on function chain no nesting - dependent

- allOf(cfs)           - all future must complete
- anyOf(cfs)           - any future completed

- exceptionally(func)   - exception only
- handle(func)          - result & exception

Exception : Once catch will not propagate

In case of nested (eg. thenRun()), if u want to throw exception out and catch together at
exceptionally of outer layer, do .join()
For example:
future1.thenRun(()->future2).exceptionally() --> Exceptionally won't catch future 2 exception
future1.thenRun(()->future2.join()).exceptionally() --> will wait for future2 to finish & catch +
throw out exception to thenRun and catch at exceptionally